<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('gbk');
E_D("DROP TABLE IF EXISTS `pre_common_plugin`;");
E_C("CREATE TABLE `pre_common_plugin` (
  `pluginid` smallint(6) unsigned NOT NULL AUTO_INCREMENT,
  `available` tinyint(1) NOT NULL DEFAULT '0',
  `adminid` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `name` varchar(40) NOT NULL DEFAULT '',
  `identifier` varchar(40) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `datatables` varchar(255) NOT NULL DEFAULT '',
  `directory` varchar(100) NOT NULL DEFAULT '',
  `copyright` varchar(100) NOT NULL DEFAULT '',
  `modules` text NOT NULL,
  `version` varchar(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`pluginid`),
  UNIQUE KEY `identifier` (`identifier`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=gbk");
E_D("replace into `pre_common_plugin` values('1','0','1','QQ互联','qqconnect','','','qqconnect/','Comsenz Inc.','a:6:{i:0;a:10:{s:4:\"name\";s:7:\"connect\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:1;a:10:{s:4:\"name\";s:7:\"spacecp\";s:4:\"menu\";s:6:\"QQ绑定\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:1:\"7\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"1\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:2;a:10:{s:4:\"name\";s:6:\"qqshow\";s:4:\"menu\";s:4:\"QQ秀\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:1:\"7\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"2\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:3;a:10:{s:4:\"name\";s:7:\"connect\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"28\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:2:{s:11:\"installtype\";s:0:\"\";s:10:\"langexists\";i:1;}}','1.17');");
E_D("replace into `pre_common_plugin` values('2','0','1','腾讯分析','cloudstat','','','cloudstat/','Comsenz Inc.','a:4:{i:0;a:10:{s:4:\"name\";s:9:\"cloudstat\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"28\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:1;a:10:{s:4:\"name\";s:9:\"cloudstat\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:1:{s:11:\"installtype\";s:0:\"\";}}','1.06');");
E_D("replace into `pre_common_plugin` values('3','0','1','SOSO表情','soso_smilies','','','soso_smilies/','Comsenz Inc.','a:4:{i:0;a:10:{s:4:\"name\";s:4:\"soso\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"28\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:1;a:10:{s:4:\"name\";s:4:\"soso\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:1:{s:11:\"installtype\";s:0:\"\";}}','1.3');");
E_D("replace into `pre_common_plugin` values('4','0','1','纵横搜索','cloudsearch','','','cloudsearch/','Comsenz Inc.','a:4:{i:0;a:10:{s:4:\"name\";s:6:\"search\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:1;a:10:{s:4:\"name\";s:10:\"search_wap\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"28\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:2:{s:11:\"installtype\";s:0:\"\";s:10:\"langexists\";i:1;}}','1.06');");
E_D("replace into `pre_common_plugin` values('5','0','1','社区QQ群','qqgroup','','','qqgroup/','Comsenz Inc.','a:3:{i:0;a:10:{s:4:\"name\";s:7:\"qqgroup\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:2:{s:11:\"installtype\";s:0:\"\";s:10:\"langexists\";i:1;}}','1.03');");
E_D("replace into `pre_common_plugin` values('6','0','1','防水墙','security','','','security/','Comsenz Inc.','a:4:{i:0;a:10:{s:4:\"name\";s:8:\"security\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"28\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"1\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:1;a:10:{s:4:\"name\";s:8:\"security\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"2\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:2:{s:11:\"installtype\";s:0:\"\";s:10:\"langexists\";i:1;}}','1.10');");
E_D("replace into `pre_common_plugin` values('7','0','1','旋风存储','xf_storage','','','xf_storage/','Comsenz Inc.','a:3:{i:0;a:10:{s:4:\"name\";s:10:\"xf_storage\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:2:{s:11:\"installtype\";s:0:\"\";s:10:\"langexists\";i:1;}}','1.04');");
E_D("replace into `pre_common_plugin` values('8','1','1','手机客户端','mobile','','','mobile/','Comsenz Inc.','a:4:{i:0;a:10:{s:4:\"name\";s:6:\"mobile\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"28\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}i:1;a:10:{s:4:\"name\";s:6:\"mobile\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:6:\"system\";i:2;s:5:\"extra\";a:2:{s:11:\"installtype\";s:0:\"\";s:10:\"langexists\";i:1;}}','1.05');");
E_D("replace into `pre_common_plugin` values('14','1','1','【DRK】LED 醒目牌','drk_ledadv','1、可调用N个版块帖子;\r\n2、可定义调用帖子数量;\r\n3、可自定义广告语;\r\n4、可仅显示帖子或仅显示自定义广告语或帖子+广告语轮显;\r\n5、根据显示内容自动单双行显示;\r\n6、卡片式/LED两种时钟选择;\r\n7、可选择投放版块;\r\n8、可选择是否全局投放:当全局投放时,版块投放无效;\r\n9、可选择上下左右滚动模式;\r\n10、可选择是否启用天气预报:效果不太美观,木办法,美工方面我是外行;\r\n11、自适应宽度。','','drk_ledadv/','要命的酒鬼','a:2:{i:0;a:10:{s:4:\"name\";s:10:\"drk_ledadv\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:5:\"extra\";a:1:{s:11:\"installtype\";s:6:\"SC_GBK\";}}','2.0');");
E_D("replace into `pre_common_plugin` values('13','1','0','wmff_虚拟在线会员','wmff_xunihuiyuan','','','wmff_xunihuiyuan/','完美枫枫','a:2:{i:0;a:10:{s:4:\"name\";s:5:\"index\";s:4:\"menu\";s:0:\"\";s:3:\"url\";s:0:\"\";s:4:\"type\";s:2:\"11\";s:7:\"adminid\";s:1:\"0\";s:12:\"displayorder\";s:1:\"0\";s:8:\"navtitle\";s:0:\"\";s:7:\"navicon\";s:0:\"\";s:10:\"navsubname\";s:0:\"\";s:9:\"navsuburl\";s:0:\"\";}s:5:\"extra\";a:2:{s:11:\"installtype\";s:6:\"SC_GBK\";s:5:\"intro\";s:1033:\"<img id=\"aimg_b9aJl\" onclick=\"zoom(this, this.src, 0, 0, 0)\" class=\"zoom\" width=\"50\" height=\"50\" src=\"http://tp1.sinaimg.cn/2678367720/180/5622188407/1\" border=\"0\" alt=\"\" /> 欢迎关注<a href=\"http://weibo.com/u/2678367720\" target=\"_blank\">@完美枫枫</a><br />\n<font color=\"#ff0000\">插件名称：虚拟在线会员</font>&nbsp; &nbsp;<font color=\"#006400\">插件版本：2.5</font>&nbsp;&nbsp;<font color=\"#000080\">插件作者：完美枫枫</font> <br />\n<font color=\"#8b0000\">插件功能：<br />\n1、设定在线人数小于指定值是虚拟；<br />\n2、可虚拟历史最高记录及日期；<br />\n3、可虚拟当前在线人数和当前会员数；<br />\n4、虚拟指定会员列表，让数据更真实。</font><br />\n插件简介：完美支持DZX2跟X2.5的虚拟在线会员插件，可以虚拟一下在线会员出来，让网站看起来更火爆，更多人气！<br />\n如意有什么疑问请登陆完美枫枫网站（ <a href=\"http://www.wanmeiff.com/\" target=\"_blank\">http://www.wanmeiff.com/</a>）交流咨询！<br />\n联系我们：QQ:565948567&nbsp;&nbsp;；阿里旺旺：完美枫枫&nbsp;&nbsp;；新浪微博<a href=\"http://weibo.com/u/2678367720\" target=\"_blank\">@完美枫枫</a><br />\n\";}}','2.5');");

require("../../inc/footer.php");
?>