<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('gbk');
E_D("DROP TABLE IF EXISTS `yyd_modules`;");
E_C("CREATE TABLE `yyd_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nid` varchar(50) DEFAULT NULL COMMENT '?????',
  `name` varchar(50) DEFAULT NULL,
  `nickname` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `default_field` varchar(200) DEFAULT NULL,
  `content` text,
  `version` varchar(10) DEFAULT NULL,
  `version_new` varchar(100) NOT NULL,
  `author` varchar(50) DEFAULT NULL,
  `date` varchar(20) DEFAULT NULL,
  `update` longtext NOT NULL,
  `status` int(1) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `order` int(11) DEFAULT NULL,
  `fields` int(2) DEFAULT NULL,
  `purview` text,
  `remark` text,
  `issent` int(2) DEFAULT NULL,
  `title_name` varchar(100) DEFAULT NULL,
  `onlyone` int(2) DEFAULT NULL,
  `index_tpl` varchar(50) DEFAULT NULL,
  `list_tpl` varchar(50) DEFAULT NULL,
  `content_tpl` varchar(50) DEFAULT NULL,
  `search_tpl` varchar(100) DEFAULT NULL,
  `article_status` int(2) DEFAULT NULL,
  `visit_type` int(2) DEFAULT NULL,
  `addtime` varchar(50) DEFAULT NULL,
  `addip` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=37 DEFAULT CHARSET=gbk");
E_D("replace into `yyd_modules` values('1','manager','管理员管理','','后台管理员管理',NULL,NULL,'1.0','1.0','TTW','2013-08-10','',NULL,'system',NULL,NULL,'a:0:{}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('6','areas','地区模块','','全国的省，市，区',NULL,NULL,'4.2','4.2','youyi','2011-11-04','',NULL,'system',NULL,NULL,'a:1:{s:5:\"areas\";a:2:{s:4:\"name\";s:8:\"地区管理\";s:6:\"result\";a:1:{s:10:\"areas_list\";a:2:{s:4:\"name\";s:8:\"地区管理\";s:3:\"url\";s:15:\"code/areas/list\";}}}}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('2','articles','文章模块','','文章管理模块',NULL,NULL,'4.2','4.2','youyi','2011-11-04','',NULL,'system',NULL,NULL,'a:1:{s:8:\"articles\";a:2:{s:4:\"name\";s:8:\"文章管理\";s:6:\"result\";a:5:{s:13:\"articles_list\";a:2:{s:4:\"name\";s:8:\"文章管理\";s:3:\"url\";s:18:\"code/articles/list\";}s:12:\"articles_new\";a:2:{s:4:\"name\";s:8:\"添加文章\";s:3:\"url\";s:17:\"code/articles/new\";}s:13:\"articles_type\";a:2:{s:4:\"name\";s:8:\"分类栏目\";s:3:\"url\";s:18:\"code/articles/type\";}s:18:\"articles_page_list\";a:2:{s:4:\"name\";s:8:\"页面列表\";s:3:\"url\";s:23:\"code/articles/page_list\";}s:17:\"articles_page_new\";a:2:{s:4:\"name\";s:8:\"添加页面\";s:3:\"url\";s:22:\"code/articles/page_new\";}}}}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('5','admin','系统管理模块','','系统管理模块',NULL,NULL,'4.2','4.2','youyi','2011-11-20','',NULL,'system',NULL,NULL,'a:2:{s:6:\"system\";a:2:{s:4:\"name\";s:8:\"系统管理\";s:6:\"result\";a:9:{s:17:\"system_clearcache\";a:2:{s:4:\"name\";s:8:\"清空缓存\";s:3:\"url\";s:17:\"system/clearcache\";}s:11:\"system_info\";a:2:{s:4:\"name\";s:8:\"系统参数\";s:3:\"url\";s:11:\"system/info\";}s:16:\"system_watermark\";a:2:{s:4:\"name\";s:8:\"图片水印\";s:3:\"url\";s:16:\"system/watermark\";}s:12:\"system_email\";a:2:{s:4:\"name\";s:8:\"邮箱设置\";s:3:\"url\";s:12:\"system/email\";}s:10:\"system_id5\";a:2:{s:4:\"name\";s:7:\"ID5设置\";s:3:\"url\";s:10:\"system/id5\";}s:14:\"system_upfiles\";a:2:{s:4:\"name\";s:8:\"图片管理\";s:3:\"url\";s:14:\"system/upfiles\";}s:18:\"system_users_admin\";a:2:{s:4:\"name\";s:10:\"管理员管理\";s:3:\"url\";s:16:\"code/users/admin\";}s:23:\"system_users_admin_type\";a:2:{s:4:\"name\";s:10:\"管理员类型\";s:3:\"url\";s:21:\"code/users/admin_type\";}s:22:\"system_users_admin_log\";a:2:{s:4:\"name\";s:10:\"管理员记录\";s:3:\"url\";s:20:\"code/users/admin_log\";}}}s:4:\"site\";a:2:{s:4:\"name\";s:8:\"站点管理\";s:6:\"result\";a:3:{s:9:\"site_list\";a:2:{s:4:\"name\";s:8:\"站点列表\";s:3:\"url\";s:16:\"system/site/list\";}s:8:\"site_new\";a:2:{s:4:\"name\";s:8:\"添加站点\";s:3:\"url\";s:15:\"system/site/new\";}s:9:\"site_menu\";a:2:{s:4:\"name\";s:8:\"菜单管理\";s:3:\"url\";s:16:\"system/site/menu\";}}}}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('3','users','用户信息管理','','用户信息管理',NULL,NULL,'3.0','3.0','dycms','2011-09-01','',NULL,'system',NULL,NULL,'a:1:{s:5:\"users\";a:2:{s:4:\"name\";s:8:\"用户管理\";s:6:\"result\";a:7:{s:10:\"users_list\";a:2:{s:4:\"name\";s:8:\"用户列表\";s:3:\"url\";s:15:\"code/users/list\";}s:9:\"users_new\";a:2:{s:4:\"name\";s:8:\"添加用户\";s:3:\"url\";s:14:\"code/users/new\";}s:10:\"users_info\";a:2:{s:4:\"name\";s:8:\"用户信息\";s:3:\"url\";s:15:\"code/users/info\";}s:10:\"users_type\";a:2:{s:4:\"name\";s:8:\"用户类型\";s:3:\"url\";s:15:\"code/users/type\";}s:9:\"users_vip\";a:2:{s:4:\"name\";s:7:\"VIP管理\";s:3:\"url\";s:14:\"code/users/vip\";}s:13:\"users_examine\";a:2:{s:4:\"name\";s:12:\"审核记录列表\";s:3:\"url\";s:18:\"code/users/examine\";}s:11:\"users_rebut\";a:2:{s:4:\"name\";s:8:\"用户举报\";s:3:\"url\";s:16:\"code/users/rebut\";}}}}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('4','linkages','联动模块','','表单的联动模块',NULL,NULL,'3.0','3.0','dycms','2011-08-01','',NULL,'system',NULL,NULL,'a:1:{s:8:\"linkages\";a:2:{s:4:\"name\";s:8:\"联动管理\";s:6:\"result\";a:1:{s:13:\"linkages_list\";a:2:{s:4:\"name\";s:8:\"联动管理\";s:3:\"url\";s:18:\"code/linkages/list\";}}}}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('19','payment','支付方式','支付方式','支付方式','',NULL,'1.0','1.0','hycms','2010-06-04','','1','payment','90',NULL,'a:1:{s:7:\"payment\";a:2:{s:4:\"name\";s:8:\"支付管理\";s:6:\"result\";a:1:{s:12:\"payment_list\";a:2:{s:4:\"name\";s:8:\"支付管理\";s:3:\"url\";s:17:\"code/payment/list\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','27.154.208.44');");
E_D("replace into `yyd_modules` values('7','message','短消息/好友模块','','短消息/好友模块',NULL,NULL,'1.6','1.6','dycms','2010-08-20','',NULL,'system',NULL,NULL,'a:1:{s:7:\"message\";a:2:{s:4:\"name\";s:6:\"短消息\";s:6:\"result\";a:1:{s:12:\"message_list\";a:2:{s:4:\"name\";s:10:\"短消息列表\";s:3:\"url\";s:17:\"code/message/list\";}}}}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1376101802',NULL);");
E_D("replace into `yyd_modules` values('8','borrow','借款模块','借款模块','借款模块','',NULL,'4.2','4.2','youyi','2011-08-20','更新了借款流程，额度管理等','1','','180',NULL,'a:1:{s:6:\"borrow\";a:2:{s:4:\"name\";s:8:\"借款管理\";s:6:\"result\";a:10:{s:10:\"borrow_all\";a:2:{s:4:\"name\";s:8:\"所有借款\";s:3:\"url\";s:11:\"code/borrow\";}s:12:\"borrow_first\";a:2:{s:4:\"name\";s:8:\"初审借款\";s:3:\"url\";s:17:\"code/borrow/first\";}s:11:\"borrow_full\";a:2:{s:4:\"name\";s:8:\"满标借款\";s:3:\"url\";s:16:\"code/borrow/full\";}s:17:\"borrow_first_flow\";a:2:{s:4:\"name\";s:8:\"流转借款\";s:3:\"url\";s:27:\"code/borrow/first&is_flow=1\";}s:12:\"borrow_repay\";a:2:{s:4:\"name\";s:8:\"逾期垫付\";s:3:\"url\";s:17:\"code/borrow/repay\";}s:13:\"borrow_amount\";a:2:{s:4:\"name\";s:8:\"借款额度\";s:3:\"url\";s:18:\"code/borrow/amount\";}s:13:\"borrow_change\";a:2:{s:4:\"name\";s:8:\"债权转让\";s:3:\"url\";s:18:\"code/borrow/change\";}s:10:\"borrow_fxc\";a:2:{s:4:\"name\";s:6:\"风险池\";s:3:\"url\";s:23:\"code/borrow/fengxianchi\";}s:11:\"borrow_tool\";a:2:{s:4:\"name\";s:8:\"检测工具\";s:3:\"url\";s:16:\"code/borrow/tool\";}s:5:\"raise\";a:2:{s:4:\"name\";s:8:\"众筹项目\";s:3:\"url\";s:17:\"code/borrow/raise\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','121.207.163.15');");
E_D("replace into `yyd_modules` values('9','account','资金账号管理','资金账号管理','资金账号管理','',NULL,'4.2','4.2','youyi','2011-11-26','在原来的基础上做了很大的升级','1','account','190',NULL,'a:1:{s:7:\"account\";a:2:{s:4:\"name\";s:8:\"资金管理\";s:6:\"result\";a:8:{s:12:\"account_list\";a:2:{s:4:\"name\";s:12:\"资金账号管理\";s:3:\"url\";s:17:\"code/account/list\";}s:11:\"account_log\";a:2:{s:4:\"name\";s:8:\"资金记录\";s:3:\"url\";s:16:\"code/account/log\";}s:12:\"account_bank\";a:2:{s:4:\"name\";s:8:\"账号管理\";s:3:\"url\";s:17:\"code/account/bank\";}s:16:\"account_recharge\";a:2:{s:4:\"name\";s:8:\"充值管理\";s:3:\"url\";s:21:\"code/account/recharge\";}s:12:\"account_cash\";a:2:{s:4:\"name\";s:8:\"提现管理\";s:3:\"url\";s:17:\"code/account/cash\";}s:20:\"account_recharge_new\";a:2:{s:4:\"name\";s:8:\"添加充值\";s:3:\"url\";s:25:\"code/account/recharge_new\";}s:11:\"account_web\";a:2:{s:4:\"name\";s:8:\"网站费用\";s:3:\"url\";s:16:\"code/account/web\";}s:13:\"account_users\";a:2:{s:4:\"name\";s:8:\"用户费用\";s:3:\"url\";s:18:\"code/account/users\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','121.207.163.15');");
E_D("replace into `yyd_modules` values('14','vote','投票系统','投票系统','投票管理','',NULL,'1.0','1.0','dwcms','2012-03-23','','0','vote','140',NULL,'a:1:{s:4:\"vote\";a:2:{s:4:\"name\";s:8:\"投票管理\";s:6:\"result\";a:2:{s:9:\"vote_list\";a:2:{s:4:\"name\";s:8:\"投票管理\";s:3:\"url\";s:14:\"code/vote/list\";}s:9:\"vote_type\";a:2:{s:4:\"name\";s:8:\"投票类型\";s:3:\"url\";s:14:\"code/vote/type\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','121.207.163.15');");
E_D("replace into `yyd_modules` values('12','credit','信用积分','信用积分','信用积分','',NULL,'3.0','3.0','dwcms','2011-11-27','2010-07-27','0','credit','130',NULL,'a:1:{s:6:\"credit\";a:2:{s:4:\"name\";s:8:\"积分管理\";s:6:\"result\";a:5:{s:11:\"credit_list\";a:2:{s:4:\"name\";s:8:\"用户积分\";s:3:\"url\";s:16:\"code/credit/list\";}s:10:\"credit_log\";a:2:{s:4:\"name\";s:8:\"积分记录\";s:3:\"url\";s:15:\"code/credit/log\";}s:11:\"credit_rank\";a:2:{s:4:\"name\";s:8:\"积分等级\";s:3:\"url\";s:16:\"code/credit/rank\";}s:11:\"credit_type\";a:2:{s:4:\"name\";s:8:\"积分类型\";s:3:\"url\";s:16:\"code/credit/type\";}s:12:\"credit_class\";a:2:{s:4:\"name\";s:8:\"积分分类\";s:3:\"url\";s:17:\"code/credit/class\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','121.207.163.15');");
E_D("replace into `yyd_modules` values('15','attestations','证明材料','证明材料','用户上传信息后台进行审核','',NULL,'4.2','4.2','youyi','2011-11-09','','1','attestations','200',NULL,'a:1:{s:12:\"attestations\";a:2:{s:4:\"name\";s:8:\"资料审核\";s:6:\"result\";a:2:{s:19:\"attestations_upload\";a:2:{s:4:\"name\";s:8:\"资料审核\";s:3:\"url\";s:24:\"code/attestations/upload\";}s:20:\"attestations_uploads\";a:2:{s:4:\"name\";s:8:\"资料上传\";s:3:\"url\";s:25:\"code/attestations/uploads\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','121.207.163.15');");
E_D("replace into `yyd_modules` values('16','approve','认证管理','认证管理','姓名，学历，手机认证等管理','',NULL,'2.0','2.0','youyi','2011-11-21','','1','','170',NULL,'a:1:{s:7:\"approve\";a:2:{s:4:\"name\";s:8:\"认证管理\";s:6:\"result\";a:4:{s:15:\"approv_realname\";a:2:{s:4:\"name\";s:8:\"实名认证\";s:3:\"url\";s:21:\"code/approve/realname\";}s:10:\"approv_sms\";a:2:{s:4:\"name\";s:8:\"手机认证\";s:3:\"url\";s:16:\"code/approve/sms\";}s:12:\"approv_video\";a:2:{s:4:\"name\";s:8:\"视频认证\";s:3:\"url\";s:18:\"code/approve/video\";}s:11:\"approv_flow\";a:2:{s:4:\"name\";s:8:\"流转认证\";s:3:\"url\";s:17:\"code/approve/flow\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','121.207.163.15');");
E_D("replace into `yyd_modules` values('22','remind','提醒设置','提醒设置','提醒设置','',NULL,'1.0','1.0','dwcms','2010-08-01','','0','remind','120',NULL,'a:1:{s:6:\"remind\";a:2:{s:4:\"name\";s:8:\"提醒设置\";s:6:\"result\";a:1:{s:11:\"remind_list\";a:2:{s:4:\"name\";s:8:\"提醒管理\";s:3:\"url\";s:16:\"code/remind/list\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','125.77.173.161');");
E_D("replace into `yyd_modules` values('20','rating','评级系统','评级系统','评级系统','',NULL,'1.0','1.0','dycms','2012-01-29','','0','rating','110',NULL,'a:1:{s:6:\"rating\";a:2:{s:4:\"name\";s:8:\"用户资料\";s:6:\"result\";a:6:{s:17:\"rating_educations\";a:2:{s:4:\"name\";s:4:\"教育\";s:3:\"url\";s:22:\"code/rating/educations\";}s:10:\"rating_job\";a:2:{s:4:\"name\";s:4:\"工作\";s:3:\"url\";s:15:\"code/rating/job\";}s:12:\"rating_house\";a:2:{s:4:\"name\";s:4:\"房产\";s:3:\"url\";s:17:\"code/rating/house\";}s:14:\"rating_company\";a:2:{s:4:\"name\";s:8:\"公司管理\";s:3:\"url\";s:19:\"code/rating/company\";}s:14:\"rating_contact\";a:2:{s:4:\"name\";s:8:\"联系方式\";s:3:\"url\";s:19:\"code/rating/contact\";}s:11:\"rating_list\";a:2:{s:4:\"name\";s:8:\"用户管理\";s:3:\"url\";s:16:\"code/rating/list\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','119.129.59.248');");
E_D("replace into `yyd_modules` values('25','scrollpic','滚动图片','滚动图片','滚动图片','',NULL,'1.0','1.0','hycms','2010-12-03','','1','scrollpic','150',NULL,'a:1:{s:9:\"scrollpic\";a:2:{s:4:\"name\";s:13:\"flash大图管理\";s:6:\"result\";a:3:{s:14:\"scrollpic_list\";a:2:{s:4:\"name\";s:8:\"列表管理\";s:3:\"url\";s:19:\"code/scrollpic/list\";}s:13:\"scrollpic_new\";a:2:{s:4:\"name\";s:8:\"添加滚动\";s:3:\"url\";s:18:\"code/scrollpic/new\";}s:14:\"scrollpic_type\";a:2:{s:4:\"name\";s:8:\"类型管理\";s:3:\"url\";s:19:\"code/scrollpic/type\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','163.179.238.148');");
E_D("replace into `yyd_modules` values('32','links','友情链接','友情链接','友情链接','',NULL,'1.0','1.0','hycms','2010-04-03','2012-02-03','1','links','80',NULL,'a:1:{s:5:\"links\";a:2:{s:4:\"name\";s:8:\"友情链接\";s:6:\"result\";a:2:{s:10:\"links_list\";a:2:{s:4:\"name\";s:12:\"友情链接列表\";s:3:\"url\";s:15:\"code/links/list\";}s:10:\"links_type\";a:2:{s:4:\"name\";s:12:\"友情链接列表\";s:3:\"url\";s:15:\"code/links/type\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','111.175.90.42');");
E_D("replace into `yyd_modules` values('28','comments','评论','评论','网站总的评论管理','',NULL,'1.9','1.9','dycms','2011-11-09','','1','comment','70',NULL,'a:1:{s:8:\"comments\";a:2:{s:4:\"name\";s:8:\"评论管理\";s:6:\"result\";a:1:{s:13:\"comments_list\";a:2:{s:4:\"name\";s:8:\"评论管理\";s:3:\"url\";s:18:\"code/comments/list\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','163.179.238.148');");
E_D("replace into `yyd_modules` values('36','ucenter','ucenter','ucenter','ucenter discuz','',NULL,'1.0','1.0','discuz','2010-04-03','','1','','0',NULL,'a:1:{s:7:\"ucenter\";a:2:{s:4:\"name\";s:7:\"UCenter\";s:6:\"result\";a:1:{s:12:\"ucenter_user\";a:2:{s:4:\"name\";s:8:\"整合设置\";s:3:\"url\";s:17:\"code/ucenter/list\";}}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1383236239','121.41.245.50');");
E_D("replace into `yyd_modules` values('31','userinfo','用户信息','用户信息','用户信息','',NULL,'2.81','2.81','DWcms','2010-08-16','','1','userinfo','160',NULL,'a:1:{s:8:\"userinfo\";a:1:{s:12:\"用户信息管理\";a:5:{s:13:\"userinfo_list\";s:8:\"信息列表\";s:12:\"userinfo_new\";s:8:\"添加信息\";s:13:\"userinfo_edit\";s:8:\"编辑信息\";s:12:\"userinfo_del\";s:8:\"删除信息\";s:13:\"userinfo_view\";s:8:\"查看信息\";}}}',NULL,NULL,NULL,NULL,'[code].html','[code]_list.html','[code]_content.html',NULL,NULL,NULL,'1376101802','58.215.254.124');");

require("../../inc/footer.php");
?>